# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





pkgdatadir = $(datadir)/sgminer
pkgincludedir = $(includedir)/sgminer
pkglibdir = $(libdir)/sgminer
pkglibexecdir = $(libexecdir)/sgminer
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_triplet = i686-pc-linux-gnu
bin_PROGRAMS = sgminer$(EXEEXT)
am__append_1 =  
am__append_2 = -DGIT_VERSION=\"$(GIT_VERSION)\"
subdir = .
DIST_COMMON = $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure COPYING ChangeLog compile config.guess \
	config.sub depcomp install-sh ltmain.sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/00gnulib.m4 \
	$(top_srcdir)/m4/extensions.m4 \
	$(top_srcdir)/m4/gnulib-common.m4 \
	$(top_srcdir)/m4/gnulib-comp.m4 \
	$(top_srcdir)/m4/include_next.m4 $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/longlong.m4 $(top_srcdir)/m4/ltoptions.m4 \
	$(top_srcdir)/m4/ltsugar.m4 $(top_srcdir)/m4/ltversion.m4 \
	$(top_srcdir)/m4/lt~obsolete.m4 $(top_srcdir)/m4/memchr.m4 \
	$(top_srcdir)/m4/memmem.m4 $(top_srcdir)/m4/mmap-anon.m4 \
	$(top_srcdir)/m4/multiarch.m4 $(top_srcdir)/m4/onceonly.m4 \
	$(top_srcdir)/m4/sigaction.m4 $(top_srcdir)/m4/signal_h.m4 \
	$(top_srcdir)/m4/signalblocking.m4 \
	$(top_srcdir)/m4/stddef_h.m4 $(top_srcdir)/m4/stdint.m4 \
	$(top_srcdir)/m4/string_h.m4 $(top_srcdir)/m4/warn-on-use.m4 \
	$(top_srcdir)/m4/wchar_t.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_sgminer_OBJECTS = sgminer-sgminer.$(OBJEXT) sgminer-api.$(OBJEXT) \
	sgminer-util.$(OBJEXT) sgminer-sha2.$(OBJEXT) \
	sgminer-logging.$(OBJEXT) sgminer-driver-opencl.$(OBJEXT) \
	sgminer-ocl.$(OBJEXT) sgminer-findnonce.$(OBJEXT) \
	sgminer-adl.$(OBJEXT) sgminer-scrypt.$(OBJEXT) \
	sgminer-darkcoin.$(OBJEXT) sgminer-qubitcoin.$(OBJEXT) \
	sgminer-fresh.$(OBJEXT) sgminer-quarkcoin.$(OBJEXT) \
	sgminer-myriadcoin-groestl.$(OBJEXT) \
	sgminer-fuguecoin.$(OBJEXT) sgminer-inkcoin.$(OBJEXT) \
	sgminer-animecoin.$(OBJEXT) sgminer-groestlcoin.$(OBJEXT) \
	sgminer-sifcoin.$(OBJEXT) sgminer-twecoin.$(OBJEXT) \
	sgminer-marucoin.$(OBJEXT)
sgminer_OBJECTS = $(am_sgminer_OBJECTS)
am__DEPENDENCIES_1 =
sgminer_DEPENDENCIES = $(am__DEPENDENCIES_1) lib/libgnu.a \
	ccan/libccan.a sph/libsph.a
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
sgminer_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(sgminer_LDFLAGS) $(LDFLAGS) -o $@
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
SCRIPTS = $(bin_SCRIPTS)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC    " $@;
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD  " $@;
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN   " $@;
SOURCES = $(sgminer_SOURCES)
DIST_SOURCES = $(sgminer_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
AM_RECURSIVE_TARGETS = $(RECURSIVE_TARGETS:-recursive=) \
	$(RECURSIVE_CLEAN_TARGETS:-recursive=) tags TAGS ctags CTAGS \
	distdir dist dist-all distcheck
ETAGS = etags
CTAGS = ctags
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /opt/sph-sgminer_fresh/missing --run aclocal-1.11
ADL_CPPFLAGS = -I.
ALLOCA = 
AMTAR = ${SHELL} /opt/sph-sgminer_fresh/missing --run tar
AM_DEFAULT_VERBOSITY = 0
APPLE_UNIVERSAL_BUILD = 0
AR = ar
AUTOCONF = ${SHELL} /opt/sph-sgminer_fresh/missing --run autoconf
AUTOHEADER = ${SHELL} /opt/sph-sgminer_fresh/missing --run autoheader
AUTOMAKE = ${SHELL} /opt/sph-sgminer_fresh/missing --run automake-1.11
AWK = mawk
BITSIZEOF_PTRDIFF_T = 
BITSIZEOF_SIG_ATOMIC_T = 
BITSIZEOF_SIZE_T = 
BITSIZEOF_WCHAR_T = 
BITSIZEOF_WINT_T = 
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -O2 -Wall -march=native
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLOPEN_FLAGS = -ldl
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GIT = git
GNULIB_MBSCASECMP = 0
GNULIB_MBSCASESTR = 0
GNULIB_MBSCHR = 0
GNULIB_MBSCSPN = 0
GNULIB_MBSLEN = 0
GNULIB_MBSNCASECMP = 0
GNULIB_MBSNLEN = 0
GNULIB_MBSPBRK = 0
GNULIB_MBSPCASECMP = 0
GNULIB_MBSRCHR = 0
GNULIB_MBSSEP = 0
GNULIB_MBSSPN = 0
GNULIB_MBSSTR = 0
GNULIB_MBSTOK_R = 0
GNULIB_MEMCHR = 1
GNULIB_MEMMEM = 1
GNULIB_MEMPCPY = 0
GNULIB_MEMRCHR = 0
GNULIB_RAWMEMCHR = 0
GNULIB_SIGACTION = 1
GNULIB_SIGNAL_H_SIGPIPE = 0
GNULIB_SIGPROCMASK = 1
GNULIB_STPCPY = 0
GNULIB_STPNCPY = 0
GNULIB_STRCASESTR = 0
GNULIB_STRCHRNUL = 0
GNULIB_STRDUP = 0
GNULIB_STRERROR = 0
GNULIB_STRERROR_R = 0
GNULIB_STRNCAT = 0
GNULIB_STRNDUP = 0
GNULIB_STRNLEN = 0
GNULIB_STRPBRK = 0
GNULIB_STRSEP = 0
GNULIB_STRSIGNAL = 0
GNULIB_STRSTR = 0
GNULIB_STRTOK_R = 0
GNULIB_STRVERSCMP = 0
GREP = /bin/grep
HAVE_DECL_MEMMEM = 1
HAVE_DECL_MEMRCHR = 1
HAVE_DECL_STRDUP = 1
HAVE_DECL_STRERROR_R = 1
HAVE_DECL_STRNDUP = 1
HAVE_DECL_STRNLEN = 1
HAVE_DECL_STRSIGNAL = 1
HAVE_DECL_STRTOK_R = 1
HAVE_INTTYPES_H = 1
HAVE_LONG_LONG_INT = 1
HAVE_MBSLEN = 0
HAVE_MEMCHR = 1
HAVE_MEMPCPY = 1
HAVE_POSIX_SIGNALBLOCKING = 1
HAVE_RAWMEMCHR = 1
HAVE_SIGACTION = 1
HAVE_SIGHANDLER_T = 1
HAVE_SIGINFO_T = 1
HAVE_SIGNED_SIG_ATOMIC_T = 
HAVE_SIGNED_WCHAR_T = 
HAVE_SIGNED_WINT_T = 
HAVE_SIGSET_T = 1
HAVE_STDINT_H = 1
HAVE_STPCPY = 1
HAVE_STPNCPY = 1
HAVE_STRCASESTR = 1
HAVE_STRCHRNUL = 1
HAVE_STRPBRK = 1
HAVE_STRSEP = 1
HAVE_STRUCT_SIGACTION_SA_SIGACTION = 1
HAVE_STRVERSCMP = 1
HAVE_SYS_BITYPES_H = 
HAVE_SYS_INTTYPES_H = 
HAVE_SYS_TYPES_H = 1
HAVE_TYPE_VOLATILE_SIG_ATOMIC_T = 1
HAVE_UNSIGNED_LONG_LONG_INT = 1
HAVE_WCHAR_H = 1
HAVE_WCHAR_T = 1
INCLUDE_NEXT = include_next
INCLUDE_NEXT_AS_FIRST_DIRECTIVE = include_next
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
JANSSON_LIBS = compat/jansson-2.5/src/.libs/libjansson.a
LD = /usr/bin/ld
LDFLAGS = 
LIBCURL_CFLAGS =  
LIBCURL_LIBS = -lcurl  
LIBGNU_LIBDEPS = 
LIBGNU_LTLIBDEPS = 
LIBOBJS = 
LIBS = -lncurses -lpthread 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAINT = #
MAKEINFO = ${SHELL} /opt/sph-sgminer_fresh/missing --run makeinfo
MATH_LIBS = -lm
MKDIR_P = /bin/mkdir -p
MM_LIBS = 
NCURSES_LIBS = 
NEXT_AS_FIRST_DIRECTIVE_SIGNAL_H = <signal.h>
NEXT_AS_FIRST_DIRECTIVE_STDDEF_H = 
NEXT_AS_FIRST_DIRECTIVE_STDINT_H = <stdint.h>
NEXT_AS_FIRST_DIRECTIVE_STRING_H = <string.h>
NEXT_SIGNAL_H = <signal.h>
NEXT_STDDEF_H = 
NEXT_STDINT_H = <stdint.h>
NEXT_STRING_H = <string.h>
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OPENCL_FLAGS = -I/opt/AMDAPP/include 
OPENCL_LIBS = -L/opt/AMDAPP/lib/x86 -lOpenCL
OTOOL = 
OTOOL64 = 
PACKAGE = sgminer
PACKAGE_BUGREPORT = veox@wemakethings.net
PACKAGE_NAME = sgminer
PACKAGE_STRING = sgminer 4.1.0
PACKAGE_TARNAME = sgminer
PACKAGE_URL = https://github.com/veox/sgminer
PACKAGE_VERSION = 4.1.0
PATH_SEPARATOR = :
PDCURSES_LIBS = 
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
PRAGMA_COLUMNS = 
PRAGMA_SYSTEM_HEADER = #pragma GCC system_header
PTHREAD_FLAGS = -lpthread
PTHREAD_LIBS = -lpthread
PTRDIFF_T_SUFFIX = 
RANLIB = ranlib
REPLACE_MEMCHR = 0
REPLACE_MEMMEM = 0
REPLACE_NULL = 0
REPLACE_STPNCPY = 0
REPLACE_STRCASESTR = 0
REPLACE_STRCHRNUL = 0
REPLACE_STRDUP = 0
REPLACE_STRERROR = 0
REPLACE_STRERROR_R = 0
REPLACE_STRNCAT = 0
REPLACE_STRNDUP = 0
REPLACE_STRNLEN = 0
REPLACE_STRSIGNAL = 0
REPLACE_STRSTR = 0
REPLACE_STRTOK_R = 0
RT_LIBS = -lrt
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
SIG_ATOMIC_T_SUFFIX = 
SIZE_T_SUFFIX = 
STDDEF_H = 
STDINT_H = 
STRIP = strip
UNDEFINE_STRTOK_R = 0
VERSION = 4.1.0
VMAJ = 4
WCHAR_T_SUFFIX = 
WINT_T_SUFFIX = 
WS2_LIBS = 
abs_builddir = /opt/sph-sgminer_fresh
abs_srcdir = /opt/sph-sgminer_fresh
abs_top_builddir = /opt/sph-sgminer_fresh
abs_top_srcdir = /opt/sph-sgminer_fresh
ac_ct_CC = gcc
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
gl_LIBOBJS = 
gl_LTLIBOBJS = 
gltests_LIBOBJS = 
gltests_LTLIBOBJS = 
gltests_WITNESS = IN_SGMINER_GNULIB_TESTS
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /opt/sph-sgminer_fresh/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
lt_ECHO = echo
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
release_info = 
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
subdirs =  compat/jansson-2.5
sysconfdir = ${prefix}/etc
target = i686-pc-linux-gnu
target_alias = 
target_cpu = i686
target_os = linux-gnu
target_vendor = pc
top_build_prefix = 
top_builddir = .
top_srcdir = .
version_info = 5:0:1
ACLOCAL_AMFLAGS = -I m4
JANSSON_CPPFLAGS = -I$(top_builddir)/compat/jansson-2.5/src -I$(top_srcdir)/compat/jansson-2.5/src
EXTRA_DIST = example.conf m4/gnulib-cache.m4 \
		  ADL_SDK/readme.txt api-example.php miner.php	\
		  API.class API.java api-example.c hexdump.c \
		  doc/API doc/FAQ doc/GPU doc/SCRYPT doc/windows-build.txt

SUBDIRS = lib compat ccan sph
sgminer_CPPFLAGS = $(PTHREAD_FLAGS) -fno-strict-aliasing \
	$(JANSSON_CPPFLAGS) -I$(top_builddir)/lib -I$(top_srcdir)/lib \
	-I/opt/AMDAPP/include  $(am__append_1) $(ADL_CPPFLAGS) $(am__append_2)
sgminer_LDFLAGS = $(PTHREAD_FLAGS)
sgminer_LDADD = $(DLOPEN_FLAGS) -lcurl   compat/jansson-2.5/src/.libs/libjansson.a -lpthread \
		  -L/opt/AMDAPP/lib/x86 -lOpenCL    \
		   -lrt -lm lib/libgnu.a ccan/libccan.a sph/libsph.a

GIT_VERSION := $(shell sh -c 'git describe --abbrev=4 --dirty')
sgminer_SOURCES := sgminer.c api.c elist.h miner.h compat.h \
	bench_block.h util.c util.h uthash.h sha2.c sha2.h logging.c \
	logging.h driver-opencl.c driver-opencl.h ocl.c ocl.h \
	findnonce.c findnonce.h adl.c adl.h adl_functions.h scrypt.c \
	scrypt.h darkcoin.c darkcoin.h qubitcoin.c qubitcoin.h fresh.c \
	fresh.h quarkcoin.c quarkcoin.h myriadcoin-groestl.c \
	myriadcoin-groestl.h fuguecoin.c fuguecoin.h inkcoin.c \
	inkcoin.h animecoin.c animecoin.h groestlcoin.c groestlcoin.h \
	sifcoin.c sifcoin.h twecoin.c twecoin.h marucoin.c marucoin.h \
	kernel/*.cl
bin_SCRIPTS = $(top_srcdir)/kernel/*.cl
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in: # $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure: # $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4): # $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in: # $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p || test -f $$p1; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
sgminer$(EXEEXT): $(sgminer_OBJECTS) $(sgminer_DEPENDENCIES) 
	@rm -f sgminer$(EXEEXT)
	$(AM_V_CCLD)$(sgminer_LINK) $(sgminer_OBJECTS) $(sgminer_LDADD) $(LIBS)
install-binSCRIPTS: $(bin_SCRIPTS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_SCRIPTS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  if test -f "$$d$$p"; then echo "$$d$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n' \
	    -e 'h;s|.*|.|' \
	    -e 'p;x;s,.*/,,;$(transform)' | sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1; } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) { files[d] = files[d] " " $$1; \
	      if (++n[d] == $(am__install_max)) { \
		print "f", d, files[d]; n[d] = 0; files[d] = "" } } \
	    else { print "f", d "/" $$4, $$1 } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	     if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	     test -z "$$files" || { \
	       echo " $(INSTALL_SCRIPT) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	       $(INSTALL_SCRIPT) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	     } \
	; done

uninstall-binSCRIPTS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_SCRIPTS)'; test -n "$(bindir)" || exit 0; \
	files=`for p in $$list; do echo "$$p"; done | \
	       sed -e 's,.*/,,;$(transform)'`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/sgminer-adl.Po
include ./$(DEPDIR)/sgminer-animecoin.Po
include ./$(DEPDIR)/sgminer-api.Po
include ./$(DEPDIR)/sgminer-darkcoin.Po
include ./$(DEPDIR)/sgminer-driver-opencl.Po
include ./$(DEPDIR)/sgminer-findnonce.Po
include ./$(DEPDIR)/sgminer-fresh.Po
include ./$(DEPDIR)/sgminer-fuguecoin.Po
include ./$(DEPDIR)/sgminer-groestlcoin.Po
include ./$(DEPDIR)/sgminer-inkcoin.Po
include ./$(DEPDIR)/sgminer-logging.Po
include ./$(DEPDIR)/sgminer-marucoin.Po
include ./$(DEPDIR)/sgminer-myriadcoin-groestl.Po
include ./$(DEPDIR)/sgminer-ocl.Po
include ./$(DEPDIR)/sgminer-quarkcoin.Po
include ./$(DEPDIR)/sgminer-qubitcoin.Po
include ./$(DEPDIR)/sgminer-scrypt.Po
include ./$(DEPDIR)/sgminer-sgminer.Po
include ./$(DEPDIR)/sgminer-sha2.Po
include ./$(DEPDIR)/sgminer-sifcoin.Po
include ./$(DEPDIR)/sgminer-twecoin.Po
include ./$(DEPDIR)/sgminer-util.Po

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC) \
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC) \
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CC) \
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

sgminer-sgminer.o: sgminer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-sgminer.o -MD -MP -MF $(DEPDIR)/sgminer-sgminer.Tpo -c -o sgminer-sgminer.o `test -f 'sgminer.c' || echo '$(srcdir)/'`sgminer.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-sgminer.Tpo $(DEPDIR)/sgminer-sgminer.Po
#	$(AM_V_CC) \
#	source='sgminer.c' object='sgminer-sgminer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-sgminer.o `test -f 'sgminer.c' || echo '$(srcdir)/'`sgminer.c

sgminer-sgminer.obj: sgminer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-sgminer.obj -MD -MP -MF $(DEPDIR)/sgminer-sgminer.Tpo -c -o sgminer-sgminer.obj `if test -f 'sgminer.c'; then $(CYGPATH_W) 'sgminer.c'; else $(CYGPATH_W) '$(srcdir)/sgminer.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-sgminer.Tpo $(DEPDIR)/sgminer-sgminer.Po
#	$(AM_V_CC) \
#	source='sgminer.c' object='sgminer-sgminer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-sgminer.obj `if test -f 'sgminer.c'; then $(CYGPATH_W) 'sgminer.c'; else $(CYGPATH_W) '$(srcdir)/sgminer.c'; fi`

sgminer-api.o: api.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-api.o -MD -MP -MF $(DEPDIR)/sgminer-api.Tpo -c -o sgminer-api.o `test -f 'api.c' || echo '$(srcdir)/'`api.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-api.Tpo $(DEPDIR)/sgminer-api.Po
#	$(AM_V_CC) \
#	source='api.c' object='sgminer-api.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-api.o `test -f 'api.c' || echo '$(srcdir)/'`api.c

sgminer-api.obj: api.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-api.obj -MD -MP -MF $(DEPDIR)/sgminer-api.Tpo -c -o sgminer-api.obj `if test -f 'api.c'; then $(CYGPATH_W) 'api.c'; else $(CYGPATH_W) '$(srcdir)/api.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-api.Tpo $(DEPDIR)/sgminer-api.Po
#	$(AM_V_CC) \
#	source='api.c' object='sgminer-api.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-api.obj `if test -f 'api.c'; then $(CYGPATH_W) 'api.c'; else $(CYGPATH_W) '$(srcdir)/api.c'; fi`

sgminer-util.o: util.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-util.o -MD -MP -MF $(DEPDIR)/sgminer-util.Tpo -c -o sgminer-util.o `test -f 'util.c' || echo '$(srcdir)/'`util.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-util.Tpo $(DEPDIR)/sgminer-util.Po
#	$(AM_V_CC) \
#	source='util.c' object='sgminer-util.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-util.o `test -f 'util.c' || echo '$(srcdir)/'`util.c

sgminer-util.obj: util.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-util.obj -MD -MP -MF $(DEPDIR)/sgminer-util.Tpo -c -o sgminer-util.obj `if test -f 'util.c'; then $(CYGPATH_W) 'util.c'; else $(CYGPATH_W) '$(srcdir)/util.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-util.Tpo $(DEPDIR)/sgminer-util.Po
#	$(AM_V_CC) \
#	source='util.c' object='sgminer-util.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-util.obj `if test -f 'util.c'; then $(CYGPATH_W) 'util.c'; else $(CYGPATH_W) '$(srcdir)/util.c'; fi`

sgminer-sha2.o: sha2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-sha2.o -MD -MP -MF $(DEPDIR)/sgminer-sha2.Tpo -c -o sgminer-sha2.o `test -f 'sha2.c' || echo '$(srcdir)/'`sha2.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-sha2.Tpo $(DEPDIR)/sgminer-sha2.Po
#	$(AM_V_CC) \
#	source='sha2.c' object='sgminer-sha2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-sha2.o `test -f 'sha2.c' || echo '$(srcdir)/'`sha2.c

sgminer-sha2.obj: sha2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-sha2.obj -MD -MP -MF $(DEPDIR)/sgminer-sha2.Tpo -c -o sgminer-sha2.obj `if test -f 'sha2.c'; then $(CYGPATH_W) 'sha2.c'; else $(CYGPATH_W) '$(srcdir)/sha2.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-sha2.Tpo $(DEPDIR)/sgminer-sha2.Po
#	$(AM_V_CC) \
#	source='sha2.c' object='sgminer-sha2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-sha2.obj `if test -f 'sha2.c'; then $(CYGPATH_W) 'sha2.c'; else $(CYGPATH_W) '$(srcdir)/sha2.c'; fi`

sgminer-logging.o: logging.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-logging.o -MD -MP -MF $(DEPDIR)/sgminer-logging.Tpo -c -o sgminer-logging.o `test -f 'logging.c' || echo '$(srcdir)/'`logging.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-logging.Tpo $(DEPDIR)/sgminer-logging.Po
#	$(AM_V_CC) \
#	source='logging.c' object='sgminer-logging.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-logging.o `test -f 'logging.c' || echo '$(srcdir)/'`logging.c

sgminer-logging.obj: logging.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-logging.obj -MD -MP -MF $(DEPDIR)/sgminer-logging.Tpo -c -o sgminer-logging.obj `if test -f 'logging.c'; then $(CYGPATH_W) 'logging.c'; else $(CYGPATH_W) '$(srcdir)/logging.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-logging.Tpo $(DEPDIR)/sgminer-logging.Po
#	$(AM_V_CC) \
#	source='logging.c' object='sgminer-logging.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-logging.obj `if test -f 'logging.c'; then $(CYGPATH_W) 'logging.c'; else $(CYGPATH_W) '$(srcdir)/logging.c'; fi`

sgminer-driver-opencl.o: driver-opencl.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-driver-opencl.o -MD -MP -MF $(DEPDIR)/sgminer-driver-opencl.Tpo -c -o sgminer-driver-opencl.o `test -f 'driver-opencl.c' || echo '$(srcdir)/'`driver-opencl.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-driver-opencl.Tpo $(DEPDIR)/sgminer-driver-opencl.Po
#	$(AM_V_CC) \
#	source='driver-opencl.c' object='sgminer-driver-opencl.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-driver-opencl.o `test -f 'driver-opencl.c' || echo '$(srcdir)/'`driver-opencl.c

sgminer-driver-opencl.obj: driver-opencl.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-driver-opencl.obj -MD -MP -MF $(DEPDIR)/sgminer-driver-opencl.Tpo -c -o sgminer-driver-opencl.obj `if test -f 'driver-opencl.c'; then $(CYGPATH_W) 'driver-opencl.c'; else $(CYGPATH_W) '$(srcdir)/driver-opencl.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-driver-opencl.Tpo $(DEPDIR)/sgminer-driver-opencl.Po
#	$(AM_V_CC) \
#	source='driver-opencl.c' object='sgminer-driver-opencl.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-driver-opencl.obj `if test -f 'driver-opencl.c'; then $(CYGPATH_W) 'driver-opencl.c'; else $(CYGPATH_W) '$(srcdir)/driver-opencl.c'; fi`

sgminer-ocl.o: ocl.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-ocl.o -MD -MP -MF $(DEPDIR)/sgminer-ocl.Tpo -c -o sgminer-ocl.o `test -f 'ocl.c' || echo '$(srcdir)/'`ocl.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-ocl.Tpo $(DEPDIR)/sgminer-ocl.Po
#	$(AM_V_CC) \
#	source='ocl.c' object='sgminer-ocl.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-ocl.o `test -f 'ocl.c' || echo '$(srcdir)/'`ocl.c

sgminer-ocl.obj: ocl.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-ocl.obj -MD -MP -MF $(DEPDIR)/sgminer-ocl.Tpo -c -o sgminer-ocl.obj `if test -f 'ocl.c'; then $(CYGPATH_W) 'ocl.c'; else $(CYGPATH_W) '$(srcdir)/ocl.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-ocl.Tpo $(DEPDIR)/sgminer-ocl.Po
#	$(AM_V_CC) \
#	source='ocl.c' object='sgminer-ocl.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-ocl.obj `if test -f 'ocl.c'; then $(CYGPATH_W) 'ocl.c'; else $(CYGPATH_W) '$(srcdir)/ocl.c'; fi`

sgminer-findnonce.o: findnonce.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-findnonce.o -MD -MP -MF $(DEPDIR)/sgminer-findnonce.Tpo -c -o sgminer-findnonce.o `test -f 'findnonce.c' || echo '$(srcdir)/'`findnonce.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-findnonce.Tpo $(DEPDIR)/sgminer-findnonce.Po
#	$(AM_V_CC) \
#	source='findnonce.c' object='sgminer-findnonce.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-findnonce.o `test -f 'findnonce.c' || echo '$(srcdir)/'`findnonce.c

sgminer-findnonce.obj: findnonce.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-findnonce.obj -MD -MP -MF $(DEPDIR)/sgminer-findnonce.Tpo -c -o sgminer-findnonce.obj `if test -f 'findnonce.c'; then $(CYGPATH_W) 'findnonce.c'; else $(CYGPATH_W) '$(srcdir)/findnonce.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-findnonce.Tpo $(DEPDIR)/sgminer-findnonce.Po
#	$(AM_V_CC) \
#	source='findnonce.c' object='sgminer-findnonce.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-findnonce.obj `if test -f 'findnonce.c'; then $(CYGPATH_W) 'findnonce.c'; else $(CYGPATH_W) '$(srcdir)/findnonce.c'; fi`

sgminer-adl.o: adl.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-adl.o -MD -MP -MF $(DEPDIR)/sgminer-adl.Tpo -c -o sgminer-adl.o `test -f 'adl.c' || echo '$(srcdir)/'`adl.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-adl.Tpo $(DEPDIR)/sgminer-adl.Po
#	$(AM_V_CC) \
#	source='adl.c' object='sgminer-adl.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-adl.o `test -f 'adl.c' || echo '$(srcdir)/'`adl.c

sgminer-adl.obj: adl.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-adl.obj -MD -MP -MF $(DEPDIR)/sgminer-adl.Tpo -c -o sgminer-adl.obj `if test -f 'adl.c'; then $(CYGPATH_W) 'adl.c'; else $(CYGPATH_W) '$(srcdir)/adl.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-adl.Tpo $(DEPDIR)/sgminer-adl.Po
#	$(AM_V_CC) \
#	source='adl.c' object='sgminer-adl.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-adl.obj `if test -f 'adl.c'; then $(CYGPATH_W) 'adl.c'; else $(CYGPATH_W) '$(srcdir)/adl.c'; fi`

sgminer-scrypt.o: scrypt.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-scrypt.o -MD -MP -MF $(DEPDIR)/sgminer-scrypt.Tpo -c -o sgminer-scrypt.o `test -f 'scrypt.c' || echo '$(srcdir)/'`scrypt.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-scrypt.Tpo $(DEPDIR)/sgminer-scrypt.Po
#	$(AM_V_CC) \
#	source='scrypt.c' object='sgminer-scrypt.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-scrypt.o `test -f 'scrypt.c' || echo '$(srcdir)/'`scrypt.c

sgminer-scrypt.obj: scrypt.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-scrypt.obj -MD -MP -MF $(DEPDIR)/sgminer-scrypt.Tpo -c -o sgminer-scrypt.obj `if test -f 'scrypt.c'; then $(CYGPATH_W) 'scrypt.c'; else $(CYGPATH_W) '$(srcdir)/scrypt.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-scrypt.Tpo $(DEPDIR)/sgminer-scrypt.Po
#	$(AM_V_CC) \
#	source='scrypt.c' object='sgminer-scrypt.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-scrypt.obj `if test -f 'scrypt.c'; then $(CYGPATH_W) 'scrypt.c'; else $(CYGPATH_W) '$(srcdir)/scrypt.c'; fi`

sgminer-darkcoin.o: darkcoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-darkcoin.o -MD -MP -MF $(DEPDIR)/sgminer-darkcoin.Tpo -c -o sgminer-darkcoin.o `test -f 'darkcoin.c' || echo '$(srcdir)/'`darkcoin.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-darkcoin.Tpo $(DEPDIR)/sgminer-darkcoin.Po
#	$(AM_V_CC) \
#	source='darkcoin.c' object='sgminer-darkcoin.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-darkcoin.o `test -f 'darkcoin.c' || echo '$(srcdir)/'`darkcoin.c

sgminer-darkcoin.obj: darkcoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-darkcoin.obj -MD -MP -MF $(DEPDIR)/sgminer-darkcoin.Tpo -c -o sgminer-darkcoin.obj `if test -f 'darkcoin.c'; then $(CYGPATH_W) 'darkcoin.c'; else $(CYGPATH_W) '$(srcdir)/darkcoin.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-darkcoin.Tpo $(DEPDIR)/sgminer-darkcoin.Po
#	$(AM_V_CC) \
#	source='darkcoin.c' object='sgminer-darkcoin.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-darkcoin.obj `if test -f 'darkcoin.c'; then $(CYGPATH_W) 'darkcoin.c'; else $(CYGPATH_W) '$(srcdir)/darkcoin.c'; fi`

sgminer-qubitcoin.o: qubitcoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-qubitcoin.o -MD -MP -MF $(DEPDIR)/sgminer-qubitcoin.Tpo -c -o sgminer-qubitcoin.o `test -f 'qubitcoin.c' || echo '$(srcdir)/'`qubitcoin.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-qubitcoin.Tpo $(DEPDIR)/sgminer-qubitcoin.Po
#	$(AM_V_CC) \
#	source='qubitcoin.c' object='sgminer-qubitcoin.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-qubitcoin.o `test -f 'qubitcoin.c' || echo '$(srcdir)/'`qubitcoin.c

sgminer-qubitcoin.obj: qubitcoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-qubitcoin.obj -MD -MP -MF $(DEPDIR)/sgminer-qubitcoin.Tpo -c -o sgminer-qubitcoin.obj `if test -f 'qubitcoin.c'; then $(CYGPATH_W) 'qubitcoin.c'; else $(CYGPATH_W) '$(srcdir)/qubitcoin.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-qubitcoin.Tpo $(DEPDIR)/sgminer-qubitcoin.Po
#	$(AM_V_CC) \
#	source='qubitcoin.c' object='sgminer-qubitcoin.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-qubitcoin.obj `if test -f 'qubitcoin.c'; then $(CYGPATH_W) 'qubitcoin.c'; else $(CYGPATH_W) '$(srcdir)/qubitcoin.c'; fi`

sgminer-fresh.o: fresh.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-fresh.o -MD -MP -MF $(DEPDIR)/sgminer-fresh.Tpo -c -o sgminer-fresh.o `test -f 'fresh.c' || echo '$(srcdir)/'`fresh.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-fresh.Tpo $(DEPDIR)/sgminer-fresh.Po
#	$(AM_V_CC) \
#	source='fresh.c' object='sgminer-fresh.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-fresh.o `test -f 'fresh.c' || echo '$(srcdir)/'`fresh.c

sgminer-fresh.obj: fresh.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-fresh.obj -MD -MP -MF $(DEPDIR)/sgminer-fresh.Tpo -c -o sgminer-fresh.obj `if test -f 'fresh.c'; then $(CYGPATH_W) 'fresh.c'; else $(CYGPATH_W) '$(srcdir)/fresh.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-fresh.Tpo $(DEPDIR)/sgminer-fresh.Po
#	$(AM_V_CC) \
#	source='fresh.c' object='sgminer-fresh.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-fresh.obj `if test -f 'fresh.c'; then $(CYGPATH_W) 'fresh.c'; else $(CYGPATH_W) '$(srcdir)/fresh.c'; fi`

sgminer-quarkcoin.o: quarkcoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-quarkcoin.o -MD -MP -MF $(DEPDIR)/sgminer-quarkcoin.Tpo -c -o sgminer-quarkcoin.o `test -f 'quarkcoin.c' || echo '$(srcdir)/'`quarkcoin.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-quarkcoin.Tpo $(DEPDIR)/sgminer-quarkcoin.Po
#	$(AM_V_CC) \
#	source='quarkcoin.c' object='sgminer-quarkcoin.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-quarkcoin.o `test -f 'quarkcoin.c' || echo '$(srcdir)/'`quarkcoin.c

sgminer-quarkcoin.obj: quarkcoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-quarkcoin.obj -MD -MP -MF $(DEPDIR)/sgminer-quarkcoin.Tpo -c -o sgminer-quarkcoin.obj `if test -f 'quarkcoin.c'; then $(CYGPATH_W) 'quarkcoin.c'; else $(CYGPATH_W) '$(srcdir)/quarkcoin.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-quarkcoin.Tpo $(DEPDIR)/sgminer-quarkcoin.Po
#	$(AM_V_CC) \
#	source='quarkcoin.c' object='sgminer-quarkcoin.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-quarkcoin.obj `if test -f 'quarkcoin.c'; then $(CYGPATH_W) 'quarkcoin.c'; else $(CYGPATH_W) '$(srcdir)/quarkcoin.c'; fi`

sgminer-myriadcoin-groestl.o: myriadcoin-groestl.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-myriadcoin-groestl.o -MD -MP -MF $(DEPDIR)/sgminer-myriadcoin-groestl.Tpo -c -o sgminer-myriadcoin-groestl.o `test -f 'myriadcoin-groestl.c' || echo '$(srcdir)/'`myriadcoin-groestl.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-myriadcoin-groestl.Tpo $(DEPDIR)/sgminer-myriadcoin-groestl.Po
#	$(AM_V_CC) \
#	source='myriadcoin-groestl.c' object='sgminer-myriadcoin-groestl.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-myriadcoin-groestl.o `test -f 'myriadcoin-groestl.c' || echo '$(srcdir)/'`myriadcoin-groestl.c

sgminer-myriadcoin-groestl.obj: myriadcoin-groestl.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-myriadcoin-groestl.obj -MD -MP -MF $(DEPDIR)/sgminer-myriadcoin-groestl.Tpo -c -o sgminer-myriadcoin-groestl.obj `if test -f 'myriadcoin-groestl.c'; then $(CYGPATH_W) 'myriadcoin-groestl.c'; else $(CYGPATH_W) '$(srcdir)/myriadcoin-groestl.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-myriadcoin-groestl.Tpo $(DEPDIR)/sgminer-myriadcoin-groestl.Po
#	$(AM_V_CC) \
#	source='myriadcoin-groestl.c' object='sgminer-myriadcoin-groestl.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-myriadcoin-groestl.obj `if test -f 'myriadcoin-groestl.c'; then $(CYGPATH_W) 'myriadcoin-groestl.c'; else $(CYGPATH_W) '$(srcdir)/myriadcoin-groestl.c'; fi`

sgminer-fuguecoin.o: fuguecoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-fuguecoin.o -MD -MP -MF $(DEPDIR)/sgminer-fuguecoin.Tpo -c -o sgminer-fuguecoin.o `test -f 'fuguecoin.c' || echo '$(srcdir)/'`fuguecoin.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-fuguecoin.Tpo $(DEPDIR)/sgminer-fuguecoin.Po
#	$(AM_V_CC) \
#	source='fuguecoin.c' object='sgminer-fuguecoin.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-fuguecoin.o `test -f 'fuguecoin.c' || echo '$(srcdir)/'`fuguecoin.c

sgminer-fuguecoin.obj: fuguecoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-fuguecoin.obj -MD -MP -MF $(DEPDIR)/sgminer-fuguecoin.Tpo -c -o sgminer-fuguecoin.obj `if test -f 'fuguecoin.c'; then $(CYGPATH_W) 'fuguecoin.c'; else $(CYGPATH_W) '$(srcdir)/fuguecoin.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-fuguecoin.Tpo $(DEPDIR)/sgminer-fuguecoin.Po
#	$(AM_V_CC) \
#	source='fuguecoin.c' object='sgminer-fuguecoin.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-fuguecoin.obj `if test -f 'fuguecoin.c'; then $(CYGPATH_W) 'fuguecoin.c'; else $(CYGPATH_W) '$(srcdir)/fuguecoin.c'; fi`

sgminer-inkcoin.o: inkcoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-inkcoin.o -MD -MP -MF $(DEPDIR)/sgminer-inkcoin.Tpo -c -o sgminer-inkcoin.o `test -f 'inkcoin.c' || echo '$(srcdir)/'`inkcoin.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-inkcoin.Tpo $(DEPDIR)/sgminer-inkcoin.Po
#	$(AM_V_CC) \
#	source='inkcoin.c' object='sgminer-inkcoin.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-inkcoin.o `test -f 'inkcoin.c' || echo '$(srcdir)/'`inkcoin.c

sgminer-inkcoin.obj: inkcoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-inkcoin.obj -MD -MP -MF $(DEPDIR)/sgminer-inkcoin.Tpo -c -o sgminer-inkcoin.obj `if test -f 'inkcoin.c'; then $(CYGPATH_W) 'inkcoin.c'; else $(CYGPATH_W) '$(srcdir)/inkcoin.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-inkcoin.Tpo $(DEPDIR)/sgminer-inkcoin.Po
#	$(AM_V_CC) \
#	source='inkcoin.c' object='sgminer-inkcoin.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-inkcoin.obj `if test -f 'inkcoin.c'; then $(CYGPATH_W) 'inkcoin.c'; else $(CYGPATH_W) '$(srcdir)/inkcoin.c'; fi`

sgminer-animecoin.o: animecoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-animecoin.o -MD -MP -MF $(DEPDIR)/sgminer-animecoin.Tpo -c -o sgminer-animecoin.o `test -f 'animecoin.c' || echo '$(srcdir)/'`animecoin.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-animecoin.Tpo $(DEPDIR)/sgminer-animecoin.Po
#	$(AM_V_CC) \
#	source='animecoin.c' object='sgminer-animecoin.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-animecoin.o `test -f 'animecoin.c' || echo '$(srcdir)/'`animecoin.c

sgminer-animecoin.obj: animecoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-animecoin.obj -MD -MP -MF $(DEPDIR)/sgminer-animecoin.Tpo -c -o sgminer-animecoin.obj `if test -f 'animecoin.c'; then $(CYGPATH_W) 'animecoin.c'; else $(CYGPATH_W) '$(srcdir)/animecoin.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-animecoin.Tpo $(DEPDIR)/sgminer-animecoin.Po
#	$(AM_V_CC) \
#	source='animecoin.c' object='sgminer-animecoin.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-animecoin.obj `if test -f 'animecoin.c'; then $(CYGPATH_W) 'animecoin.c'; else $(CYGPATH_W) '$(srcdir)/animecoin.c'; fi`

sgminer-groestlcoin.o: groestlcoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-groestlcoin.o -MD -MP -MF $(DEPDIR)/sgminer-groestlcoin.Tpo -c -o sgminer-groestlcoin.o `test -f 'groestlcoin.c' || echo '$(srcdir)/'`groestlcoin.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-groestlcoin.Tpo $(DEPDIR)/sgminer-groestlcoin.Po
#	$(AM_V_CC) \
#	source='groestlcoin.c' object='sgminer-groestlcoin.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-groestlcoin.o `test -f 'groestlcoin.c' || echo '$(srcdir)/'`groestlcoin.c

sgminer-groestlcoin.obj: groestlcoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-groestlcoin.obj -MD -MP -MF $(DEPDIR)/sgminer-groestlcoin.Tpo -c -o sgminer-groestlcoin.obj `if test -f 'groestlcoin.c'; then $(CYGPATH_W) 'groestlcoin.c'; else $(CYGPATH_W) '$(srcdir)/groestlcoin.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-groestlcoin.Tpo $(DEPDIR)/sgminer-groestlcoin.Po
#	$(AM_V_CC) \
#	source='groestlcoin.c' object='sgminer-groestlcoin.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-groestlcoin.obj `if test -f 'groestlcoin.c'; then $(CYGPATH_W) 'groestlcoin.c'; else $(CYGPATH_W) '$(srcdir)/groestlcoin.c'; fi`

sgminer-sifcoin.o: sifcoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-sifcoin.o -MD -MP -MF $(DEPDIR)/sgminer-sifcoin.Tpo -c -o sgminer-sifcoin.o `test -f 'sifcoin.c' || echo '$(srcdir)/'`sifcoin.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-sifcoin.Tpo $(DEPDIR)/sgminer-sifcoin.Po
#	$(AM_V_CC) \
#	source='sifcoin.c' object='sgminer-sifcoin.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-sifcoin.o `test -f 'sifcoin.c' || echo '$(srcdir)/'`sifcoin.c

sgminer-sifcoin.obj: sifcoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-sifcoin.obj -MD -MP -MF $(DEPDIR)/sgminer-sifcoin.Tpo -c -o sgminer-sifcoin.obj `if test -f 'sifcoin.c'; then $(CYGPATH_W) 'sifcoin.c'; else $(CYGPATH_W) '$(srcdir)/sifcoin.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-sifcoin.Tpo $(DEPDIR)/sgminer-sifcoin.Po
#	$(AM_V_CC) \
#	source='sifcoin.c' object='sgminer-sifcoin.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-sifcoin.obj `if test -f 'sifcoin.c'; then $(CYGPATH_W) 'sifcoin.c'; else $(CYGPATH_W) '$(srcdir)/sifcoin.c'; fi`

sgminer-twecoin.o: twecoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-twecoin.o -MD -MP -MF $(DEPDIR)/sgminer-twecoin.Tpo -c -o sgminer-twecoin.o `test -f 'twecoin.c' || echo '$(srcdir)/'`twecoin.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-twecoin.Tpo $(DEPDIR)/sgminer-twecoin.Po
#	$(AM_V_CC) \
#	source='twecoin.c' object='sgminer-twecoin.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-twecoin.o `test -f 'twecoin.c' || echo '$(srcdir)/'`twecoin.c

sgminer-twecoin.obj: twecoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-twecoin.obj -MD -MP -MF $(DEPDIR)/sgminer-twecoin.Tpo -c -o sgminer-twecoin.obj `if test -f 'twecoin.c'; then $(CYGPATH_W) 'twecoin.c'; else $(CYGPATH_W) '$(srcdir)/twecoin.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-twecoin.Tpo $(DEPDIR)/sgminer-twecoin.Po
#	$(AM_V_CC) \
#	source='twecoin.c' object='sgminer-twecoin.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-twecoin.obj `if test -f 'twecoin.c'; then $(CYGPATH_W) 'twecoin.c'; else $(CYGPATH_W) '$(srcdir)/twecoin.c'; fi`

sgminer-marucoin.o: marucoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-marucoin.o -MD -MP -MF $(DEPDIR)/sgminer-marucoin.Tpo -c -o sgminer-marucoin.o `test -f 'marucoin.c' || echo '$(srcdir)/'`marucoin.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-marucoin.Tpo $(DEPDIR)/sgminer-marucoin.Po
#	$(AM_V_CC) \
#	source='marucoin.c' object='sgminer-marucoin.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-marucoin.o `test -f 'marucoin.c' || echo '$(srcdir)/'`marucoin.c

sgminer-marucoin.obj: marucoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sgminer-marucoin.obj -MD -MP -MF $(DEPDIR)/sgminer-marucoin.Tpo -c -o sgminer-marucoin.obj `if test -f 'marucoin.c'; then $(CYGPATH_W) 'marucoin.c'; else $(CYGPATH_W) '$(srcdir)/marucoin.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/sgminer-marucoin.Tpo $(DEPDIR)/sgminer-marucoin.Po
#	$(AM_V_CC) \
#	source='marucoin.c' object='sgminer-marucoin.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(sgminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sgminer-marucoin.obj `if test -f 'marucoin.c'; then $(CYGPATH_W) 'marucoin.c'; else $(CYGPATH_W) '$(srcdir)/marucoin.c'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(MKDIR_P) "$(distdir)/$$subdir" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod u+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(PROGRAMS) $(SCRIPTS) config.h
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic clean-libtool mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am:

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-binPROGRAMS install-binSCRIPTS

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-binSCRIPTS

.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) all \
	ctags-recursive install-am install-strip tags-recursive

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am am--refresh check check-am clean clean-binPROGRAMS \
	clean-generic clean-libtool ctags ctags-recursive dist \
	dist-all dist-bzip2 dist-gzip dist-lzma dist-shar dist-tarZ \
	dist-xz dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-binSCRIPTS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs installdirs-am maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags tags-recursive uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-binSCRIPTS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
